"use client";
import Head from "next/head";
import TodoApp from "@/conponents/TodoApp";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section className="flex justify-center items-center h-screen">
        <TodoApp />
      </section>
    </div>
  );
}
